---
name: nexus

releases:
- name: nexus
  version: 0.9.0
  url: https://github.com/making/nexus-boshrelease/releases/download/0.9.0/nexus-boshrelease-0.9.0.tgz
  sha1: 2e0cbb0b40f5b9598cc89a5f097c0afa27725285

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3468.latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: micro
  persist_disk: default
  stemcell: default
  azs: [z1]
  networks:
  - name: default
#    static_ips: [((internal_ip))]
  jobs:
  - name: nexus
    release: nexus
    properties:
      nexus:
        heap_size: 768M
        max_direct_memory_size: 512M
  - name: nexus-backup
    release: nexus

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
