---
name: instant-https

releases:
- name: instant-https
  version: latest
  # sha1: 404a50accba52ee0d6e3d04b9da4ae1484646b2d
  # url: https://github.com/govau/instant-https-boshrelease/releases/download/v4.1.0/instant-https-4.1.0.tgz

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3468.latest

instance_groups:
- name: https_proxy
  instances: 1
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: proxy
    release: instant-https
    properties:
      contact_email: ((contact_email))
      dns_providers:
        googlecloud:
          GCE_PROJECT: ((gce_project))
          GCE_SERVICE_ACCOUNT_FILE: ((gce_service_account_file))
      proxies:
      - hostnames: ((ci_hostnames))
        acme_url: ((acme_url))
        backends: ((ci_backends))
        websocket: true
      - hostnames: ((opsman_hostnames))
        acme_url: ((acme_url))
        backends: ((opsman_backends))
        insecure_skip_verify: true
      - hostnames: ((pas_hostnames))
        backends: ((pas_backends))
        acme_url: ((acme_url))
        websocket: true
        insecure_skip_verify: true
        dns_provider: googlecloud
      - hostnames: ((harbor_hostnames))
        backends: ((harbor_backends))
        acme_url: ((acme_url))
        insecure_skip_verify: true
  vm_type: micro
  stemcell: default

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
